using Noo.Api.AssignedWorks.Models;
using Noo.Api.AssignedWorks.Services;
using Noo.Api.AssignedWorks.Types;
using Noo.Api.Works.Models;
using Noo.Api.Works.Types;

namespace Noo.UnitTests.AssignedWorks;

/// <summary>
/// The expected scores below are the ground truth produced by the original
/// web-2.0 checking algorithm. They are generated by
/// ../../tests/generate-task-check-cases.mjs (run with node), which copies the
/// check functions verbatim from web-2.0 TaskService and emits
/// task-check-cases.psv. The pipe-separated rows from that file are pasted
/// into <see cref="Cases"/>; regenerate and re-paste to refresh.
/// </summary>
public class TaskCheckServiceTests
{
    // check strategy|right answers|answer|score|max score
    private const string Cases = """
        ExactMatchOrZero|Moscow|Moscow|10|10
        ExactMatchOrZero|Moscow|moscow|10|10
        ExactMatchOrZero|Moscow|MOSCOW|10|10
        ExactMatchOrZero|Moscow|  moscow  |10|10
        ExactMatchOrZero|Moscow|M o s c o w|10|10
        ExactMatchOrZero|Moscow|Moscov|0|10
        ExactMatchOrZero|Moscow||0|10
        ExactMatchOrZero|Red,Green,Blue|green|5|5
        ExactMatchOrZero|Red,Green,Blue|GREEN|5|5
        ExactMatchOrZero|Red,Green,Blue|yellow|0|5
        ExactMatchOrZero|Привет|привет|3|3
        ExactMatchOrZero|Привет|ПРИВЕТ|3|3
        ExactMatchOrZero|Привет|привед|0|3
        ExactMatchWithWrongCharacter|cat|cat|6|6
        ExactMatchWithWrongCharacter|cat|CAT|6|6
        ExactMatchWithWrongCharacter|cat| C a t |6|6
        ExactMatchWithWrongCharacter|cat|cot|5|6
        ExactMatchWithWrongCharacter|cat|dog|3|6
        ExactMatchWithWrongCharacter|cat|ca|5|6
        ExactMatchWithWrongCharacter|cat|cats|5|6
        ExactMatchWithWrongCharacter|cat|catssss|2|6
        ExactMatchWithWrongCharacter|cat||0|6
        ExactMatchWithWrongCharacter|Banana|banana|4|4
        ExactMatchWithWrongCharacter|Banana|bananx|3|4
        ExactMatchWithWrongCharacter|Banana|bxnxnx|1|4
        ExactMatchWithWrongCharacter|Banana,Apple|apple|4|4
        ExactMatchWithWrongCharacter|Banana,Apple|aprle|3|4
        MultipleChoice|abc|abc|9|9
        MultipleChoice|abc|cba|9|9
        MultipleChoice|abc|CBA|9|9
        MultipleChoice|abc| a b c |9|9
        MultipleChoice|abc|abx|8|9
        MultipleChoice|abc|ab|8|9
        MultipleChoice|abc|abcd|8|9
        MultipleChoice|abc|abcde|7|9
        MultipleChoice|abc|xyz|6|9
        MultipleChoice|1234|4321|8|8
        MultipleChoice|1234|1243|8|8
        MultipleChoice|1234|124|7|8
        MultipleChoice|1234|12345|7|8
        MultipleChoice|abc,xyz|zyx|9|9
        Sequence|hello|hello|10|10
        Sequence|hello|HELLO|10|10
        Sequence|hello| h e l l o |10|10
        Sequence|hello|hallo|9|10
        Sequence|hello|hallu|9|10
        Sequence|hello|hxxxo|0|10
        Sequence|hello|hell|8|10
        Sequence|hello|helloo|8|10
        Sequence|hello|hellooo|7|10
        Sequence|hello||0|10
        Sequence|world|word|5|7
        Sequence|world|wrld|0|7
        Sequence|world|worldwide|0|7
        Sequence|hello,hallo|hallo|10|10
        Sequence|hello,world|wordl|6|7
        """;

    public static TheoryData<WorkTaskCheckStrategy, string[], string, int, int> CheckCases()
    {
        var data = new TheoryData<WorkTaskCheckStrategy, string[], string, int, int>();

        foreach (var line in Cases.Split('\n', StringSplitOptions.RemoveEmptyEntries))
        {
            var columns = line.Split('|');
            var strategy = Enum.Parse<WorkTaskCheckStrategy>(columns[0]);
            var rightAnswers = columns[1].Split(',', StringSplitOptions.RemoveEmptyEntries);
            var answer = columns[2];
            var expectedScore = int.Parse(columns[3]);
            var maxScore = int.Parse(columns[4]);

            data.Add(strategy, rightAnswers, answer, expectedScore, maxScore);
        }

        return data;
    }

    [Theory]
    [MemberData(nameof(CheckCases))]
    public void CheckTasks_MatchesWeb2Reference(
        WorkTaskCheckStrategy strategy,
        string[] rightAnswers,
        string answer,
        int expectedScore,
        int maxScore)
    {
        var service = new TaskCheckService();

        var task = new WorkTaskModel
        {
            Id = Ulid.NewUlid(),
            Type = WorkTaskType.Word,
            CheckStrategy = strategy,
            RightAnswers = rightAnswers,
            MaxScore = maxScore,
        };

        var workAnswer = new AssignedWorkAnswerModel
        {
            TaskId = task.Id,
            Status = AssignedWorkAnswerStatus.Submitted,
            WordContent = answer,
        };

        var score = service.CheckTasks(new[] { workAnswer }, new[] { task });

        Assert.Equal(expectedScore, score);

        // The answer is passed by reference and must carry its own computed score.
        Assert.Equal(expectedScore, workAnswer.Score);
    }

    [Fact]
    public void CheckTasks_IgnoresNonSubmittedAnswers()
    {
        var service = new TaskCheckService();

        var task = new WorkTaskModel
        {
            Id = Ulid.NewUlid(),
            Type = WorkTaskType.Word,
            CheckStrategy = WorkTaskCheckStrategy.ExactMatchOrZero,
            RightAnswers = new[] { "answer" },
            MaxScore = 10,
        };

        var workAnswer = new AssignedWorkAnswerModel
        {
            TaskId = task.Id,
            Status = AssignedWorkAnswerStatus.NotSubmitted,
            WordContent = "answer",
        };

        var score = service.CheckTasks(new[] { workAnswer }, new[] { task });

        Assert.Equal(0, score);
        Assert.Null(workAnswer.Score);
    }

    [Fact]
    public void CheckTasks_SkipsManuallyCheckedTaskTypes()
    {
        var service = new TaskCheckService();

        // Essay is not automatically checkable, so it must never contribute a score.
        var task = new WorkTaskModel
        {
            Id = Ulid.NewUlid(),
            Type = WorkTaskType.Essay,
            CheckStrategy = WorkTaskCheckStrategy.ExactMatchOrZero,
            RightAnswers = new[] { "answer" },
            MaxScore = 10,
        };

        var workAnswer = new AssignedWorkAnswerModel
        {
            TaskId = task.Id,
            Status = AssignedWorkAnswerStatus.Submitted,
            WordContent = "answer",
        };

        var score = service.CheckTasks(new[] { workAnswer }, new[] { task });

        Assert.Equal(0, score);
        Assert.Null(workAnswer.Score);
    }

    [Fact]
    public void CheckTasks_SumsScoresAcrossMultipleTasks()
    {
        var service = new TaskCheckService();

        var firstTask = new WorkTaskModel
        {
            Id = Ulid.NewUlid(),
            Type = WorkTaskType.Word,
            CheckStrategy = WorkTaskCheckStrategy.ExactMatchOrZero,
            RightAnswers = new[] { "Moscow" },
            MaxScore = 10,
        };

        var secondTask = new WorkTaskModel
        {
            Id = Ulid.NewUlid(),
            Type = WorkTaskType.Word,
            CheckStrategy = WorkTaskCheckStrategy.ExactMatchWithWrongCharacter,
            RightAnswers = new[] { "cat" },
            MaxScore = 6,
        };

        var answers = new[]
        {
            new AssignedWorkAnswerModel
            {
                TaskId = firstTask.Id,
                Status = AssignedWorkAnswerStatus.Submitted,
                WordContent = "moscow",
            },
            new AssignedWorkAnswerModel
            {
                TaskId = secondTask.Id,
                Status = AssignedWorkAnswerStatus.Submitted,
                WordContent = "cot",
            },
        };

        var score = service.CheckTasks(answers, new[] { firstTask, secondTask });

        // 10 (exact match) + 5 (one wrong character) = 15
        Assert.Equal(15, score);

        // Each answer must hold the score computed for its own task.
        Assert.Equal(10, answers[0].Score);
        Assert.Equal(5, answers[1].Score);
    }
}
